/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (BloodyRoar2Recomp)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SCUS-94424 (USA) boot EXE entry PC (probe seed) */
#define PSX_FN_BootEntryUsa 0x80126174u
#define func_80126174 BootEntryUsa  /* alias */

/* guessed: SLES-01722 (Europe) boot EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80126178u
#define func_80126178 BootEntry  /* alias */
